apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ip-address-pool.yaml
  - l2-advertisement.yaml

commonLabels:
  app.kubernetes.io/name: metallb
  app.kubernetes.io/managed-by: homelab-platform
  app.kubernetes.io/part-of: metallb