apiVersion: v1
kind: Endpoints
metadata:
  name: windows-exporter
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.0.100.110
    ports:
      - name: metrics
        port: 9182
        protocol: TCP